Connect to session on background thread now causes an error. It does not cause an error if you revert back to 2.14.2 version.
2019-03-13 09:41:16.863 4073-4107/com.tokbox.android.tutorials.basic_video_chat E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.tokbox.android.tutorials.basic_video_chat, PID: 4073
    java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
        at android.os.Handler.<init>(Handler.java:234)
        at android.os.Handler.<init>(Handler.java:141)
        at android.telephony.PhoneStateListener$1.<init>(PhoneStateListener.java:317)
        at android.telephony.PhoneStateListener.<init>(PhoneStateListener.java:317)
        at android.telephony.PhoneStateListener.<init>(PhoneStateListener.java:287)
        at com.opentok.android.DefaultAudioDevice$3.<init>(DefaultAudioDevice.java:217)
        at com.opentok.android.DefaultAudioDevice.<init>(DefaultAudioDevice.java:217)
        at com.opentok.android.AudioDeviceManager.initializeDefaultDevice(AudioDeviceManager.java:60)
        at com.opentok.android.Session.<init>(Session.java:738)
        at com.opentok.android.Session$Builder.build(Session.java:602)
        at com.tokbox.android.tutorials.basic_video_chat.MainActivity$1.run(MainActivity.java:158)